name: Build and Push to Docker Hub
on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight


jobs:
  docker:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Install PowerShell
        run: |
          # Import the Microsoft signing key
          wget -q https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb

          # Update the package list and install PowerShell
          sudo apt-get update
          sudo apt-get install -y powershell
      -
        name: Run Prepare-Build.ps1 Script
        run: pwsh Prepare-Build.ps1
      -
        name: Buildx
        run: ./nginx-proxy-manager/scripts/buildx
      -
        name: Push to Docker Hub
        run: ./nginx-proxy-manager/scripts/buildx
      